fix: close server application context
without it:

 ./gradlew :test-suite-http-server-tck-gcp-function-http-test:test --parallel --rerun-tasks --no-daemon --no-build-cache

```
           Caused by:
                io.netty.channel.ChannelException: failed to open a new selector
                    at app//io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:179)
                    at app//io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:146)
                    at app//io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:183)
                    at app//io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:38)
                    at app//io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
                    ... 47 more

                    Caused by:
                    java.io.IOException: Too many open files
                        at java.base/sun.nio.ch.IOUtil.makePipe(Native Method)
                        at java.base/sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:86)
                        at java.base/sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:36)
                        at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
                        ... 51 more
```